### ISSUE TITLE
Navigation Box doesn't work with Internet Explorer

### ISSUE THREAD

**Issue by atlarep** [samuelet/indexmenu#156] opened 2016-08-17 21:29 UTC
When I use Internet Explorer, the navigation box only shows a few namespaces as links (no icons and NS won't expand).
Any suggestions?

Using Chrome:
![image](https://cloud.githubusercontent.com/assets/20726009/17753919/12b1711a-64a0-11e6-8a00-f0afbbc6dcd4.png)

Using IE:
![image](https://cloud.githubusercontent.com/assets/20726009/17753881/dfdf0ba8-649f-11e6-952a-b3e40360e9b7.png)

**Comment by Klap-in** [comment] 2016-08-17 22:30
That looks like the fall back version of the js version of the indexmenu.
I assume that JavaScript is enabled?
Could you check if the console in the Developer tool of the browser(or what for that purpose is included in IE) has errors?

**Comment by atlarep** [comment] 2016-08-18 14:22
I just confirmed it is enabled.
The Developer Console doesn't show any errors.
![image](https://cloud.githubusercontent.com/assets/20726009/17777118/513c84f0-652d-11e6-9f1c-1459cb0742b5.png)

**Comment by atlarep** [comment] 2016-08-22 16:06
Any word on this?

**Comment by Klap-in** [comment] 2016-08-22 21:35
Is your wiki reachable from internet?

**Comment by atlarep** [comment] 2016-08-23 16:20
No. It is only for internal/company use.

**Comment by atlarep** [comment] 2016-09-02 20:48
Any word on this?

**Comment by Klap-in** [comment] 2016-09-02 21:47
@atlarep sorry, but at the moment I have not an windows installation in combination with a wiki to test this. 

@samuelet do you have any change to test this case? Reproducing and minimizing the scope of this issue would be already useful!

**Comment by samuelet** [comment] 2016-09-03 20:28
@atlarep Could you report the dokuwiki version, the list of installed plugins and the version of the IE that you tested not working?

**Comment by atlarep** [comment] 2016-09-06 21:41
This is what I have in the syntax for the nav page: 
`{{indexmenu>..#1|js#bj-tango.png navbar max#3#2}}`
DokuWiki version: `Release 2016-06-26a "Elenor of Tsort"`
IE version: `11.0.9600.18426 (update version 11.0.34)`
Template: Vector
Plugins: 
```
Addnewpage
Authad
Autostartpage
Bookcreator
Ckgedit
Custombuttons
Discussion
Dw2pdf
Editx
Filelist
Gallery
Groupmanager
Imgpaste
Indexmenu
Infomail
Loadskin
Mediaattachment
Medialist
Move
Nsexport
Nspages
Odt
Orphanswanted
Pagelist
Recommend
Smtp
Socialite
Swiftmail
Talkpage
Tools
Wrap

```

**Comment by atlarep** [comment] 2016-09-29 19:24
Any word on this?

**Comment by samuelet** [comment] 2016-10-04 19:56
I can't reproduce it on windows 10 IE 11.87 and vector template.
I've to say that all reported plugins are not tested, but i'd expect a console error from an incompatible plugin.
Just to be sure: do you correctly display the js indexmenu on http://samuele.netsons.org/dokuwiki/doku.php form the same web client ?
I'll go further with tests , in the meanwhile:

**Comment by atlarep** [comment] 2016-10-05 20:28
Yeah, I've tested with different servers. The issue seems to be occurring to me with IE only. 
I am using IE version 11.0.9600.18449
Update versions 11.0.35 (KB3185319)

**Comment by Tabrisange** [comment] 2017-01-26 14:55
I have the same problem !

**Comment by Klap-in** [comment] 2020-07-11 19:11
Is there any info in the debugging console of the browser from the javasript? without errors it not doable to guess what is going on.

**Comment by Klap-in** [comment] 2020-07-11 19:12
Is the Edge browser working?

**Comment by rgleason** [comment] 2020-07-31 10:48
I have something similar happening here on Opencpn.  
https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:opencpn_user_manual

The full indexmenu is not showing, and navigation becomes more difficult.
This started happening shortly after I clicked on a upgrade for chkedit, which caused the ADMIN dropdown to disappear and not be available so I cannot do any admin and cannot log out or log back in.

**Comment by Klap-in** [comment] 2020-07-31 14:00
About the admin, can you check the log of your webserver? I guess a 500 error is happening somewhere.

(Btw, you mean cgkedit plugin?)

**Comment by rgleason** [comment] 2020-07-31 14:16
I will do that. Thanks.   Yes cgkedit

**Comment by rgleason** [comment] 2020-08-02 23:49
I found error.log and the most recent errors are all: 
[31-Jul-2020 15:34:13 UTC] PHP Warning:  Illegal string offset 'abstract' in /home/szlhykiz/public_html/wiki/dokuwiki/feed.php on line 406
...
[02-Aug-2020 13:25:06 UTC] PHP Warning:  Illegal string offset 'abstract' in /home/szlhykiz/public_html/wiki/dokuwiki/feed.php on line 406

Before that
[21-Jun-2020 20:32:40 UTC] PHP Warning:  getimagesize(/home/szlhykiz/public_html/wiki/dokuwiki/data/media_attic/opencpn/manual/squiddio_overall1.1592616119.png): failed to open stream: Permission denied in /home/szlhykiz/public_html/wiki/dokuwiki/inc/media.php on line 1083

**Comment by Klap-in** [comment] 2020-08-02 23:59
This looks not as an obvious issue. Info found sofas: 
https://github.com/splitbrain/dokuwiki/issues/3182
https://forum.dokuwiki.org/d/18109-php-error-warnings-in-feedphp
So not something that helps you at the moment.

**Comment by rgleason** [comment] 2020-08-03 00:43
Klap in  Virk suggested adding  ?do=admin  to the end, which got me in!
Virk Your suggestion works for me with this url "https://opencpn.org/wiki/dokuwiki/doku.php?do=admin"

Then I changed the Template from bootstrap3 to the more reliable docuwiki template, so the dropdown menu for admin is no longer hidden.   

I also disabled  cgkedit and find that the menu is still shortened and does not really provide the kind of navigation we need.
See https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:opencpn_user_manual
The config page has indexmenu settings:
no optimization
plugin»indexmenu»headpage   check :start  check :inside  check :same  can be any of this value :opencpn
hide headpages checked.
The page that will replace the main dokuwiki index  :opencpn:sidebar 
Plugin skip file   /(:blank$|^blank.txt$)/
Show to admins the indexmenu sort bar  checked

I the sidebar page we have 
{{indexmenu>:opencpn#1|js#drktheme navbar msort nsort}}

which has worked very well for many years.

**Comment by rgleason** [comment] 2020-08-03 00:50
I think I saw a note about putting something in the code for JS that would make it work.
Ah Ha, it is here  https://github.com/samuelet/indexmenu/issues/232#issuecomment-667718184
Is this something that might work?  We are now the most current of Hogfather.

```
The Hogfather release of DokuWiki does now default used deferred loading of javascript.
The indexmenu plugin does have inline javascript, which is not compatible with deferred loading of javascript.
So to let it work, you have to use the feature flag 'defer_js' in the Configuration Manager.

If you use this feature flag, according to my information the indexmenu plugin should just work. If you see other issues, please report here.

```

I will look for this flag now.

**Comment by rgleason** [comment] 2020-08-03 01:01
Found this 

defer_jsDefer  javascript to be execute after the page's HTML has been parsed.  Improves perceived page speed but could break a small number of plugins.
--

and unchecked it.  And it is all working well, will reenable ckgedit now..  Thank you!
https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:opencpn_user_manual

**Comment by Klap-in** [comment] 2020-08-03 06:34
In the newest version of indexmenu I added a message that explains this step. I hope it reduce the time to a solution.

**Comment by rgleason** [comment] 2020-08-03 13:35
Thanks Klap-in, since I did not open this (atlarp did), I can't and shouldn't close it.  However it may be instructive to others.

**Comment by Klap-in** [comment] 2021-07-18 23:22
Closed by lack of info. Further, the Internet Explorer browser is replaced by the Edge browser.

**Closed by Klap-in** 2021-07-18 23:22 UTC
Labels: needstriage
