### ISSUE TITLE
Sorting fails with subpage

### ISSUE THREAD

**Issue by distahl** [samuelet/indexmenu#202] opened 2019-05-09 05:27 UTC
Hi,

I'm not sure if I do something wrong, but this is my issue.
I'm having a list like this:

```
MainTitle
  1. Page1
  2. Page2
  3. Page3
  4. Page4
```

This working like inteded. But if I add a subpage to one of those, the sorting fails:

```
MainTitle
  3. Page3
    Subpage3
  1. Page1
  2. Page2
  4. Page4
```

The list is created with this line:
```{{indexmenu>:SomeTitle:MainTitle#2|tsort}}```

Is this a bug or am I doing something wrong?

**Comment by Klap-in** [comment] 2020-07-11 18:24
Could you maybe try:
`{{indexmenu>:SomeTitle:MainTitle#2|nsort tsort}}`
Does this improve your situation? nsort sorts the namespaces with the same sorting.

**Comment by distahl** [comment] 2020-07-14 06:47
No, unfortunately isn't changing anything.

**Comment by Klap-in** [comment] 2023-12-27 14:03
You see this:
![image](https://github.com/samuelet/indexmenu/assets/183250/cef864d5-717c-4709-b4c2-fe23295c7feb)
(however, this is shown using useheading=never setting, but with `tsort` option)

What happens is that first the namespaces are are sorted, next the pages from that namespace (in this case from namespace SomeTitle:maintitle).

A aspect which makes this behaviour less clear is that nodes of a namespace will get a link to the page that is recognized as "headpage" according to the enabled `headpage` setting (options :same:, :inside:, :start: or custom).

Sorting of namespace together with the pages is requested in #66 as well.

**Comment by Klap-in** [comment] 2024-01-02 23:27
Duplicate of #66

**Closed by Klap-in** 2024-01-02 23:27 UTC
Labels: bug
