### ISSUE TITLE
indexmenu don't work after upgrade to 'Elenor of Tsort'

### ISSUE THREAD

**Issue by Future001** [samuelet/indexmenu#154] opened 2016-07-15 23:04 UTC
Site could not be found after upgrade. I'm using following code

{{indexmenu>..#1|js#thread navbar max#3#2 msort tsort msort}}

I'm german so there are many Capital words and the after upgrade process the reference goes to the the pages with lower case! This pages are now empty!

Please fix this...

**Comment by polyzen** [comment] 2016-08-02 15:12
Perhaps the same issue? splitbrain/dokuwiki#1652

**Comment by samuelet** [comment] 2016-09-11 09:52
I can't reproduce it, is it resolved with latest updates? Or can you post a screenshot?

**Comment by Future001** [comment] 2016-09-27 22:45
Hello there,
today I tried it again, but have no luck.
After the update process via the update plugin, the indexmenu can't find any site. If you compare screenshot 1 and 2 you will see, that the headlines after upgrading are shown in plain text with "-" between the words and no wiki site can be found any more. Bevore upgrading, I updated every single plugin to the newest version. I'm using the indexmenü plugin in the sidebar as a automatic navigation panel with following syntax: {{indexmenu>..#1|js#thread navbar max#3#2 msort tsort msort}}
![screenshot1](https://cloud.githubusercontent.com/assets/9453794/18894686/99bac3c0-8514-11e6-8b93-2f75d9f771e2.jpg)
![screenshot2](https://cloud.githubusercontent.com/assets/9453794/18894687/99bc38ae-8514-11e6-9473-2b8448d09310.jpg)

hope you can help!

**Comment by Future001** [comment] 2016-09-29 19:09
Hi there (again),

got it. I already forgot - I 'hacked' the inc/pageutils.php (Line 128) ages ago.... and upgrading dokuwiki resets this.
watch this: https://forum.dokuwiki.org/thread/495

SOLVED! :)

**Closed** 2020-07-11 19:13 UTC
